quarkus.rest-client.situacao-cadastral-api.url=http://localhost:8181

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=lucas
quarkus.datasource.password=22461016
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/agencia